# Generated by Django 4.0.1 on 2022-01-23 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_bookmark_like_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='like_count',
        ),
    ]
